//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EmployeeToolModels;

namespace EmployeeManagement.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int Id { get; set; }
        public Nullable<double> salary_amount_paid { get; set; }
        public Nullable<System.DateTime> salaryDate { get; set; }
        public Nullable<int> Fk_EmployeeId { get; set; }
    
        public virtual EmployeeModel EmployeeModel { get; set; }
    }
}
